POST http://127.0.0.1:3000/movie/add HTTP/1.1
Content-Type: application/json

{
    "openingDate":"2021-01-01",
    "title":"Avengers_test",
    "grade":5,
    "still_shots": "1.jpg,2.jpg",
    "description":"test",
    "modifier":"root"
}
###

GET http://localhost:3000/movie/list?page=1 HTTP/1.1
###

DELETE http://localhost:3000/movie/3 HTTP/1.1
###


PATCH  http://localhost:3000/movie/1 HTTP/1.1
Content-Type: application/json

{
  "openingDate":"2021-01-01",
  "title":"update-test",
  "grade":5,
  "stillShots":"1.jpg,3.jpg",
  "description":"blablabla",
  "modifier":"root"
}